In [1]:
import numpy as np
import pandas as pd
import GEOparse

from sklearn.model_selection import train_test_split, GroupKFold, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.decomposition import PCA
from tensorflow.keras import layers, Model, regularizers
import tensorflow as tf
from tensorflow.keras import layers, Model, regularizers
from sklearn.decomposition import PCA
from sklearn.metrics import classification_report
from sklearn.metrics.pairwise import euclidean_distances
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report
from sklearn.decomposition import PCA
from sklearn.metrics.pairwise import euclidean_distances
import tensorflow as tf
from tensorflow.keras import layers, Model, regularizers
import numpy as np
import pandas as pd
import tensorflow as tf

from tensorflow.keras import layers, Model, regularizers
from sklearn.decomposition import PCA
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.metrics import classification_report


from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    matthews_corrcoef,
    make_scorer
)

C:\Users\cihan\ki-al-miRNA-attack\venv\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

In [2]:
gse = GEOparse.get_GEO("GSE68951", destdir="../data")
print(gse)

16-Jan-2026 18:13:03 DEBUG utils - Directory ../data already exists. Skipping.
16-Jan-2026 18:13:03 INFO GEOparse - File already exist: using local version.
16-Jan-2026 18:13:03 INFO GEOparse - Parsing ../data\GSE68951_family.soft.gz:
16-Jan-2026 18:13:03 DEBUG GEOparse - DATABASE: GeoMiame
16-Jan-2026 18:13:03 DEBUG GEOparse - SERIES: GSE68951
16-Jan-2026 18:13:03 DEBUG GEOparse - PLATFORM: GPL16770
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688368
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688369
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688370
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688371
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688372
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688373
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688374
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688375
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688376
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688377
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688378
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688379
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688380
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688381
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688382
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688383
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688384
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688385
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688386
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688387
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688388
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688389
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688390
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688391
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688392
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688393
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688394
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688395
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688396
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688397
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688398
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688399
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688400
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688401
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688402
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688403
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688404
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688405
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688406
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688407
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688408
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688409
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688410
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688411
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688412
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688413
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688414
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688415
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688416
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688417
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688418
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688419
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688420
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688421
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688422
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688423
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688424
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688425
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688426
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688427
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688428
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688429
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688430
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688431
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688432
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688433
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688434
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688435
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688436
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688437
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688438
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688439
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688440
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688441
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688442
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688443
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688444
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688445
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688446
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688447
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688448
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688449
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688450
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688451
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688452
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688453
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688454
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688455
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688456
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688457
16-Jan-2026 18:13:03 DEBUG GEOparse - SAMPLE: GSM1688458
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688459
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688460
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688461
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688462
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688463
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688464
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688465
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688466
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688467
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688468
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688469
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688470
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688471
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688472
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688473
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688474
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688475
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688476
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688477
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688478
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688479
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688480
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688481
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688482
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688483
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688484
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688485
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688486
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688487
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688488
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688489
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688490
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688491
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688492
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688493
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688494
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688495
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688496
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688497
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688498
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688499
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688500
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688501
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688502
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688503
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688504
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688505
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688506
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688507
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688508
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688509
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688510
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688511
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688512
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688513
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688514
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688515
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688516
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688517
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688518
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688519
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688520
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688521
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688522
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688523
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688524
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688525
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688526
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688527
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688528
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688529
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688530
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688531
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688532
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688533
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688534
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688535
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688536
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688537
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688538
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688539
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688540
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688541
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688542
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688543
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688544
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688545
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688546
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688547
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688548
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688549
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688550
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688551
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688552
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688553
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688554
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688555
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688556
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688557
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688558
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688559
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688560
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688561
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688562
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688563
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688564
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688565
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688566
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688567
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688568
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688569
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688570
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688571
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688572
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688573
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688574
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688575
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688576
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688577
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688578
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688579
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688580
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688581
16-Jan-2026 18:13:04 DEBUG GEOparse - SAMPLE: GSM1688582

<SERIES: GSE68951 - 215 SAMPLES, 1 d(s)>

In [3]:
sample = gse.gsms["GSM1688406"]
sample.table.tail()

            ID_REF     VALUE
1200   hsa-miR-100  1.936057
1201   hsa-miR-101  4.114362
1202  hsa-miR-1289  1.735477
1203  hsa-miR-1288  2.192123
1204   hsa-miR-105  1.285812

In [4]:
def extract_full_info(gse):

    data = [] 
    for gsm_id, sample in gse.gsms.items():

        meta = sample.metadata["characteristics_ch1"]

        patient_id, timepoint, disease = None, None, None
        
        for item in meta:
            if item.startswith("patient id"):
                patient_id = item.split(":")[1].strip()
            if item.startswith("timepoint"):
                timepoint = int(item.split(":")[1].strip())
            if item.startswith("disease"):
                disease = item.split(":")[1].strip()
        if patient_id is None or timepoint is None:
            continue

        mirnas = sample.table["ID_REF"].values
        expr   = sample.table["VALUE"].values.astype(float)

        data.append({
            "gsm": gsm_id,
            "patient": patient_id,
            "timepoint": timepoint,
            "mirna_names": mirnas,
            "expression": expr
        })

    return pd.DataFrame(data)

In [5]:
df_all = extract_full_info(gse)
df_all.head()

,gsm,patient,timepoint,mirna_names,expression
0,GSM1688368,A,1,"[hsa-miR-507, hsa-miR-548d-5p, hsa-miR-1976, h...","[1.854979099, 2.184182338, 2.532296403, 1.5180..."
1,GSM1688369,A,2,"[hsa-miR-507, hsa-miR-548d-5p, hsa-miR-1976, h...","[1.469763084, 2.320244044, 2.111889095, 1.6172..."
2,GSM1688370,A,3,"[hsa-miR-507, hsa-miR-548d-5p, hsa-miR-1976, h...","[1.44937518, 2.510284729, 2.083508284, 1.23588..."
3,GSM1688371,A,4,"[hsa-miR-507, hsa-miR-548d-5p, hsa-miR-1976, h...","[1.777522456, 2.724678628, 3.012721615, 1.3907..."
4,GSM1688372,A,5,"[hsa-miR-507, hsa-miR-548d-5p, hsa-miR-1976, h...","[1.538218176, 2.030509973, 2.470374907, 1.5635..."

In [6]:
# Feature matrix
X = np.vstack(df_all["expression"].values)

# Labels = patient identity
y = df_all["patient"].astype("category").cat.codes.values

# Groups = patient (CV kontrolü için)
groups = df_all["patient"].values

In [7]:
df_all.groupby("patient").size()

patient
A              8
B              8
C              8
D              8
E              8
F              8
G              8
H              7
I              8
J              8
K              8
L              8
M              8
N              8
O              8
P              8
Q              8
R              8
S              7
T              8
U              8
V              8
W              8
X              7
Y              8
Z              6
ZZ_control    12
dtype: int64

In [8]:
scaler_classifier = make_pipeline(
    StandardScaler(),
    LogisticRegression(max_iter=5000)
)

In [9]:
def evaluate_model_logreg(X, y, classifier=None): #NAIVE METHOD

    if classifier is None:
        classifier = LogisticRegression(max_iter=5000)

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.3,
        random_state=42,
        stratify=y
    )

    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)

    print(classification_report(y_test, y_pred, zero_division=0))

    return classifier

In [10]:
cfg = evaluate_model_logreg(X, y, scaler_classifier)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00         2
           2       0.67      1.00      0.80         2
           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00         3
           5       0.33      0.50      0.40         2
           6       0.00      0.00      0.00         3
           7       0.00      0.00      0.00         2
           8       0.00      0.00      0.00         3
           9       0.33      0.50      0.40         2
          10       0.00      0.00      0.00         2
          11       0.00      0.00      0.00         3
          12       0.00      0.00      0.00         2
          13       0.00      0.00      0.00         2
          14       0.50      0.50      0.50         2
          15       0.00      0.00      0.00         3
          16       0.50      0.50      0.50         2
          17       0.00      0.00      0.00         2
          18       0.50      0.50      0.50         2
          19       0.00      0.00      0.00         3
          20       0.00      0.00      0.00         2
          21       0.50      0.33      0.40         3
          22       0.33      0.67      0.44         3
          23       1.00      1.00      1.00         2
          24       1.00      0.50      0.67         2
          25       0.00      0.00      0.00         2
          26       1.00      0.50      0.67         4

    accuracy                           0.23        65
   macro avg       0.25      0.24      0.23        65
weighted avg       0.25      0.23      0.23        65

In [11]:
groups

array(['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'D', 'D',
       'D', 'D', 'D', 'D', 'D', 'D', 'E', 'E', 'E', 'E', 'E', 'E', 'E',
       'E', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'G', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'I', 'I',
       'I', 'I', 'I', 'I', 'I', 'I', 'J', 'J', 'J', 'J', 'J', 'J', 'J',
       'J', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'L', 'L', 'L', 'L',
       'L', 'L', 'L', 'L', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'N',
       'N', 'N', 'N', 'N', 'N', 'N', 'N', 'O', 'O', 'O', 'O', 'O', 'O',
       'O', 'O', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'Q', 'Q', 'Q',
       'Q', 'Q', 'Q', 'Q', 'Q', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'T', 'T', 'T', 'T', 'T', 'T',
       'T', 'T', 'U', 'U', 'U', 'U', 'U', 'U', 'U', 'U', 'V', 'V', 'V',
       'V', 'V', 'V', 'V', 'V', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W',
       'X', 'X', 'X', 'X', 'X', 'X', 'X', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Z', 'Z', 'Z', 'Z', 'Z', 'Z', 'ZZ_control', 'ZZ_control',
       'ZZ_control', 'ZZ_control', 'ZZ_control', 'ZZ_control',
       'ZZ_control', 'ZZ_control', 'ZZ_control', 'ZZ_control',
       'ZZ_control', 'ZZ_control'], dtype=object)

In [12]:
def evaluate_model_logreg_groupKFold(X, y, groups): #Actually does not suit our problem at hand at all cause KFold is an open-set classification

    gkf = GroupKFold(n_splits=5)
    accuracies = []
    f1s = []
    fold = 1

    clf = make_pipeline(
        StandardScaler(),
        LogisticRegression(max_iter=5000)
    )

    for train_idx, test_idx in gkf.split(X, y, groups):

        print(f"\n====== Fold {fold} ======")

        X_train, X_test = X[train_idx], X[test_idx]
        y_train, y_test = y[train_idx], y[test_idx]

        clf.fit(X_train, y_train)
        y_pred = clf.predict(X_test)

        acc = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred, average="macro", zero_division=0)

        print("Accuracy:", acc)
        print("F1 macro:", f1)
        print(classification_report(y_test, y_pred, zero_division=0))

        accuracies.append(acc)
        f1s.append(f1)
        fold += 1

    print("\n=== FINAL LOGREG ===")
    print("Mean Accuracy:", np.mean(accuracies))
    print("Mean F1 Macro:", np.mean(f1s))

In [13]:
evaluate_model_logreg_groupKFold(X, y, groups)
(X, y, groups)

====== Fold 1 ======
Accuracy: 0.0
F1 macro: 0.0
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           1       0.00      0.00      0.00       8.0
           2       0.00      0.00      0.00       0.0
           7       0.00      0.00      0.00       0.0
          11       0.00      0.00      0.00       0.0
          12       0.00      0.00      0.00       8.0
          13       0.00      0.00      0.00       0.0
          14       0.00      0.00      0.00       8.0
          17       0.00      0.00      0.00       0.0
          18       0.00      0.00      0.00       7.0
          19       0.00      0.00      0.00       0.0
          21       0.00      0.00      0.00       0.0
          22       0.00      0.00      0.00       0.0
          24       0.00      0.00      0.00       0.0
          26       0.00      0.00      0.00      12.0

    accuracy                           0.00      43.0
   macro avg       0.00      0.00      0.00      43.0
weighted avg       0.00      0.00      0.00      43.0


====== Fold 2 ======
Accuracy: 0.0
F1 macro: 0.0
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           1       0.00      0.00      0.00       0.0
           2       0.00      0.00      0.00       8.0
           4       0.00      0.00      0.00       0.0
           5       0.00      0.00      0.00       0.0
           7       0.00      0.00      0.00       0.0
           9       0.00      0.00      0.00       0.0
          10       0.00      0.00      0.00       0.0
          11       0.00      0.00      0.00       8.0
          12       0.00      0.00      0.00       0.0
          15       0.00      0.00      0.00       8.0
          16       0.00      0.00      0.00       0.0
          17       0.00      0.00      0.00       0.0
          20       0.00      0.00      0.00       8.0
          21       0.00      0.00      0.00       0.0
          22       0.00      0.00      0.00       0.0
          24       0.00      0.00      0.00       8.0
          25       0.00      0.00      0.00       6.0

    accuracy                           0.00      46.0
   macro avg       0.00      0.00      0.00      46.0
weighted avg       0.00      0.00      0.00      46.0


====== Fold 3 ======
Accuracy: 0.0
F1 macro: 0.0
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       8.0
           1       0.00      0.00      0.00       0.0
           2       0.00      0.00      0.00       0.0
           3       0.00      0.00      0.00       0.0
           4       0.00      0.00      0.00       0.0
           6       0.00      0.00      0.00       8.0
           7       0.00      0.00      0.00       0.0
           8       0.00      0.00      0.00       0.0
           9       0.00      0.00      0.00       0.0
          10       0.00      0.00      0.00       8.0
          11       0.00      0.00      0.00       0.0
          13       0.00      0.00      0.00       0.0
          14       0.00      0.00      0.00       0.0
          17       0.00      0.00      0.00       0.0
          18       0.00      0.00      0.00       0.0
          19       0.00      0.00      0.00       8.0
          20       0.00      0.00      0.00       0.0
          22       0.00      0.00      0.00       8.0
          25       0.00      0.00      0.00       0.0
          26       0.00      0.00      0.00       0.0

    accuracy                           0.00      40.0
   macro avg       0.00      0.00      0.00      40.0
weighted avg       0.00      0.00      0.00      40.0


====== Fold 4 ======
Accuracy: 0.0
F1 macro: 0.0
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           1       0.00      0.00      0.00       0.0
           2       0.00      0.00      0.00       0.0
           3       0.00      0.00      0.00       8.0
           4       0.00      0.00      0.00       0.0
           5       0.00      0.00      0.00       8.0
           9       0.00      0.00      0.00       8.0
          13       0.00      0.00      0.00       0.0
          15       0.00      0.00      0.00       0.0
          16       0.00      0.00      0.00       8.0
          17       0.00      0.00      0.00       8.0
          18       0.00      0.00      0.00       0.0
          20       0.00      0.00      0.00       0.0
          22       0.00      0.00      0.00       0.0
          25       0.00      0.00      0.00       0.0

    accuracy                           0.00      40.0
   macro avg       0.00      0.00      0.00      40.0
weighted avg       0.00      0.00      0.00      40.0


====== Fold 5 ======
Accuracy: 0.0
F1 macro: 0.0
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           2       0.00      0.00      0.00       0.0
           4       0.00      0.00      0.00       8.0
           6       0.00      0.00      0.00       0.0
           7       0.00      0.00      0.00       7.0
           8       0.00      0.00      0.00       8.0
           9       0.00      0.00      0.00       0.0
          10       0.00      0.00      0.00       0.0
          11       0.00      0.00      0.00       0.0
          12       0.00      0.00      0.00       0.0
          13       0.00      0.00      0.00       8.0
          15       0.00      0.00      0.00       0.0
          17       0.00      0.00      0.00       0.0
          18       0.00      0.00      0.00       0.0
          19       0.00      0.00      0.00       0.0
          21       0.00      0.00      0.00       8.0
          22       0.00      0.00      0.00       0.0
          23       0.00      0.00      0.00       7.0
          25       0.00      0.00      0.00       0.0
          26       0.00      0.00      0.00       0.0

    accuracy                           0.00      46.0
   macro avg       0.00      0.00      0.00      46.0
weighted avg       0.00      0.00      0.00      46.0


=== FINAL LOGREG ===
Mean Accuracy: 0.0
Mean F1 Macro: 0.0

(array([[1.8549791 , 2.18418234, 2.5322964 , ..., 1.41000193, 3.72745529,
         1.37007761],
        [1.46976308, 2.32024404, 2.11188909, ..., 1.4279172 , 2.45035886,
         1.35776645],
        [1.44937518, 2.51028473, 2.08350828, ..., 1.12366167, 2.571076  ,
         1.06683767],
        ...,
        [1.55135439, 2.09630509, 1.84061179, ..., 1.46840623, 4.03715339,
         0.933782  ],
        [1.58819243, 2.44854081, 2.43935147, ..., 1.26001547, 3.43739097,
         1.32423004],
        [1.96891928, 2.30610466, 2.02487855, ..., 1.21281883, 3.98844345,
         0.86618795]], shape=(215, 1205)),
 array([ 0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  2,
         2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,
         4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,
         6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,
         8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10,
        10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12,
        12, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14,
        15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 17,
        17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19,
        19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21,
        21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23,
        23, 23, 24, 24, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25, 26,
        26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26], dtype=int8),
 array(['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B',
        'B', 'B', 'B', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'D', 'D',
        'D', 'D', 'D', 'D', 'D', 'D', 'E', 'E', 'E', 'E', 'E', 'E', 'E',
        'E', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'G', 'G', 'G', 'G',
        'G', 'G', 'G', 'G', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'I', 'I',
        'I', 'I', 'I', 'I', 'I', 'I', 'J', 'J', 'J', 'J', 'J', 'J', 'J',
        'J', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'L', 'L', 'L', 'L',
        'L', 'L', 'L', 'L', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'N',
        'N', 'N', 'N', 'N', 'N', 'N', 'N', 'O', 'O', 'O', 'O', 'O', 'O',
        'O', 'O', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'Q', 'Q', 'Q',
        'Q', 'Q', 'Q', 'Q', 'Q', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'T', 'T', 'T', 'T', 'T', 'T',
        'T', 'T', 'U', 'U', 'U', 'U', 'U', 'U', 'U', 'U', 'V', 'V', 'V',
        'V', 'V', 'V', 'V', 'V', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W',
        'X', 'X', 'X', 'X', 'X', 'X', 'X', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
        'Y', 'Y', 'Z', 'Z', 'Z', 'Z', 'Z', 'Z', 'ZZ_control', 'ZZ_control',
        'ZZ_control', 'ZZ_control', 'ZZ_control', 'ZZ_control',
        'ZZ_control', 'ZZ_control', 'ZZ_control', 'ZZ_control',
        'ZZ_control', 'ZZ_control'], dtype=object))

In [14]:
import numpy as np
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

def run_basic_svm_baseline(X, y, test_size=0.2, random_state=42):
    """
    Naive SVM baseline (NOT attack-consistent).
    Purpose: sanity check that SVM can learn from the data.
    """

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=test_size,
        stratify=y,
        random_state=random_state
    )

    pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("pca", PCA(n_components=0.95)),
        ("svm", SVC(
            kernel="rbf",
            C=1.0,
            gamma="scale"
        ))
    ])

    pipeline.fit(X_train, y_train)
    y_pred = pipeline.predict(X_test)

    print("Naive SVM baseline (random split)")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred, zero_division=0))

    return pipeline

In [15]:
run_basic_svm_baseline(X,y)

Naive SVM baseline (random split)
Accuracy: 0.18604651162790697
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         2
           2       1.00      0.50      0.67         2
           3       0.33      0.50      0.40         2
           4       0.00      0.00      0.00         2
           5       0.50      0.50      0.50         2
           6       0.00      0.00      0.00         2
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         2
           9       0.33      1.00      0.50         1
          10       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         2
          12       0.00      0.00      0.00         1
          13       0.00      0.00      0.00         2
          14       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         2
          16       0.00      0.00      0.00         2
          17       0.00      0.00      0.00         1
          18       0.00      0.00      0.00         1
          19       0.00      0.00      0.00         2
          20       0.00      0.00      0.00         2
          21       0.25      1.00      0.40         1
          22       0.00      0.00      0.00         2
          23       1.00      1.00      1.00         1
          24       0.00      0.00      0.00         2
          25       0.00      0.00      0.00         1
          26       1.00      1.00      1.00         2

    accuracy                           0.19        43
   macro avg       0.16      0.20      0.17        43
weighted avg       0.17      0.19      0.16        43

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=0.95)),
                ('svm', SVC())])

In [16]:
def build_svm_pca_pipeline():
    return Pipeline([
        ("scaler", StandardScaler()),
        ("pca", PCA()),
        ("svm", SVC(kernel="rbf"))
    ])

In [17]:
def tune_hyperparameters(pipeline, X, y, groups):

    param_grid = {
        "pca__n_components": [5, 10, 15, 20],
        "svm__C": [0.1, 1, 10],
        "svm__gamma": ["scale", 0.01, 0.001]
    }

    mcc_scorer = make_scorer(matthews_corrcoef)
    gkf = GroupKFold(n_splits=5)

    grid = GridSearchCV(
        estimator=pipeline,
        param_grid=param_grid,
        scoring=mcc_scorer,
        cv=gkf.split(X, y, groups),
        n_jobs=-1,
        verbose=2
    )

    grid.fit(X, y)

    print("Best Params:", grid.best_params_)
    print("Best MCC:", grid.best_score_)

    return grid.best_estimator_

In [18]:
def evaluate_model(model, X, y, groups):

    gkf = GroupKFold(n_splits=5)
    accuracies = []
    f1s = []
    fold = 1

    for train_idx, test_idx in gkf.split(X, y, groups):

        print(f"\n====== Fold {fold} ======")

        X_train, X_test = X[train_idx], X[test_idx]
        y_train, y_test = y[train_idx], y[test_idx]

        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        acc = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred, average="macro", zero_division=0)

        print("Accuracy:", acc)
        print("F1:", f1)
        print(classification_report(y_test, y_pred, zero_division=0))

        accuracies.append(acc)
        f1s.append(f1)
        fold += 1

    print("\nFINAL RESULTS")
    print("Mean Accuracy:", np.mean(accuracies))
    print("Mean F1 Macro:", np.mean(f1s))

In [19]:
def run_svm_pca_experiment(X, y, groups):

    print("Building model")
    pipeline = build_svm_pca_pipeline()

    print("Tuning hyperparameters")
    best_model = tune_hyperparameters(pipeline, X, y, groups)

    print("Evaluating final model")
    evaluate_model(best_model, X, y, groups)

    return best_model

In [20]:
best_model = run_svm_pca_experiment(X, y, groups)

Building model
Tuning hyperparameters
Fitting 5 folds for each of 36 candidates, totalling 180 fits
Best Params: {'pca__n_components': 5, 'svm__C': 0.1, 'svm__gamma': 'scale'}
Best MCC: 0.0
Evaluating final model

====== Fold 1 ======
Accuracy: 0.0
F1: 0.0
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           1       0.00      0.00      0.00       8.0
           2       0.00      0.00      0.00       0.0
           4       0.00      0.00      0.00       0.0
           5       0.00      0.00      0.00       0.0
           8       0.00      0.00      0.00       0.0
           9       0.00      0.00      0.00       0.0
          10       0.00      0.00      0.00       0.0
          11       0.00      0.00      0.00       0.0
          12       0.00      0.00      0.00       8.0
          13       0.00      0.00      0.00       0.0
          14       0.00      0.00      0.00       8.0
          16       0.00      0.00      0.00       0.0
          17       0.00      0.00      0.00       0.0
          18       0.00      0.00      0.00       7.0
          19       0.00      0.00      0.00       0.0
          21       0.00      0.00      0.00       0.0
          26       0.00      0.00      0.00      12.0

    accuracy                           0.00      43.0
   macro avg       0.00      0.00      0.00      43.0
weighted avg       0.00      0.00      0.00      43.0


====== Fold 2 ======
Accuracy: 0.0
F1: 0.0
              precision    recall  f1-score   support

           2       0.00      0.00      0.00       8.0
          11       0.00      0.00      0.00       8.0
          15       0.00      0.00      0.00       8.0
          20       0.00      0.00      0.00       8.0
          24       0.00      0.00      0.00       8.0
          25       0.00      0.00      0.00       6.0
          26       0.00      0.00      0.00       0.0

    accuracy                           0.00      46.0
   macro avg       0.00      0.00      0.00      46.0
weighted avg       0.00      0.00      0.00      46.0


====== Fold 3 ======
Accuracy: 0.0
F1: 0.0
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       8.0
           6       0.00      0.00      0.00       8.0
          10       0.00      0.00      0.00       8.0
          19       0.00      0.00      0.00       8.0
          22       0.00      0.00      0.00       8.0
          26       0.00      0.00      0.00       0.0

    accuracy                           0.00      40.0
   macro avg       0.00      0.00      0.00      40.0
weighted avg       0.00      0.00      0.00      40.0


====== Fold 4 ======
Accuracy: 0.0
F1: 0.0
              precision    recall  f1-score   support

           3       0.00      0.00      0.00       8.0
           5       0.00      0.00      0.00       8.0
           9       0.00      0.00      0.00       8.0
          16       0.00      0.00      0.00       8.0
          17       0.00      0.00      0.00       8.0
          26       0.00      0.00      0.00       0.0

    accuracy                           0.00      40.0
   macro avg       0.00      0.00      0.00      40.0
weighted avg       0.00      0.00      0.00      40.0


====== Fold 5 ======
Accuracy: 0.0
F1: 0.0
              precision    recall  f1-score   support

           4       0.00      0.00      0.00       8.0
           7       0.00      0.00      0.00       7.0
           8       0.00      0.00      0.00       8.0
          13       0.00      0.00      0.00       8.0
          21       0.00      0.00      0.00       8.0
          23       0.00      0.00      0.00       7.0
          26       0.00      0.00      0.00       0.0

    accuracy                           0.00      46.0
   macro avg       0.00      0.00      0.00      46.0
weighted avg       0.00      0.00      0.00      46.0


FINAL RESULTS
Mean Accuracy: 0.0
Mean F1 Macro: 0.0

In [21]:
import numpy as np
import pandas as pd

import GEOparse

from sklearn.model_selection import train_test_split, GroupKFold, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.decomposition import PCA

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    matthews_corrcoef,
    make_scorer
)

In [22]:
g = df_all.groupby("patient")
first = next(iter(g))
type(first), len(first)

(tuple, 2)

In [23]:
def reidentification_cv(df): #patient-aware LOOCV
    for patient, df_p in df.groupby("patient"):
        for test_idx in df_p.index:
            train_idx = df.index.difference([test_idx]) #Assume that one timepoint for each patient is an unknown profile (test data).
            yield train_idx.to_numpy(), np.array([test_idx])

In [24]:
from sklearn.metrics import classification_report

clf = Pipeline([
    ("scaler", StandardScaler()),
    ("pca", PCA(n_components=0.9)),  # %90 variance
    ("logreg", LogisticRegression(max_iter=5000))
])


y_true_all = []
y_pred_all = []

for fold, (train_idx, test_idx) in enumerate(reidentification_cv(df_all), 1):

    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)

    y_true_all.extend(y_test)
    y_pred_all.extend(y_pred)

report = classification_report(
    y_true_all,
    y_pred_all,
    output_dict=True,
    zero_division=0
)

report_df = pd.DataFrame(report).transpose()
report_df

              precision    recall  f1-score     support
0              0.000000  0.000000  0.000000    8.000000
1              0.214286  0.375000  0.272727    8.000000
2              0.411765  0.875000  0.560000    8.000000
3              0.750000  0.375000  0.500000    8.000000
4              0.500000  0.250000  0.333333    8.000000
5              0.600000  0.750000  0.666667    8.000000
6              0.400000  0.250000  0.307692    8.000000
7              0.600000  0.428571  0.500000    7.000000
8              0.600000  0.375000  0.461538    8.000000
9              0.714286  0.625000  0.666667    8.000000
10             0.500000  0.125000  0.200000    8.000000
11             0.333333  0.375000  0.352941    8.000000
12             1.000000  0.375000  0.545455    8.000000
13             0.400000  0.500000  0.444444    8.000000
14             1.000000  0.750000  0.857143    8.000000
15             0.500000  0.375000  0.428571    8.000000
16             0.500000  0.375000  0.428571    8.000000
17             0.384615  0.625000  0.476190    8.000000
18             0.833333  0.714286  0.769231    7.000000
19             0.857143  0.750000  0.800000    8.000000
20             0.750000  0.375000  0.500000    8.000000
21             0.625000  0.625000  0.625000    8.000000
22             0.666667  0.750000  0.705882    8.000000
23             1.000000  0.857143  0.923077    7.000000
24             0.857143  0.750000  0.800000    8.000000
25             0.000000  0.000000  0.000000    6.000000
26             0.750000  0.500000  0.600000   12.000000
accuracy       0.488372  0.488372  0.488372    0.488372
macro avg      0.583243  0.486111  0.508338  215.000000
weighted avg   0.588592  0.488372  0.511669  215.000000

In [25]:
from sklearn.metrics import classification_report

clf_svm = Pipeline([
    ("scaler", StandardScaler()),
    ("pca", PCA(n_components=0.9)),
    ("svm", SVC(
        kernel="rbf",
        C=10,
        gamma="scale",
        class_weight="balanced"
    ))
])

y_true_all_svm = []
y_pred_all_svm = []

for fold, (train_idx, test_idx) in enumerate(reidentification_cv(df_all), 1):

    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    clf_svm.fit(X_train, y_train)
    y_pred = clf_svm.predict(X_test)

    y_true_all_svm.extend(y_test)
    y_pred_all_svm.extend(y_pred)

report_svm = classification_report(
    y_true_all_svm,
    y_pred_all_svm,
    output_dict=True,
    zero_division=0
)

report_svm_df = pd.DataFrame(report_svm).transpose()
report_svm_df

              precision    recall  f1-score     support
0              0.050000  0.125000  0.071429    8.000000
1              0.235294  0.500000  0.320000    8.000000
2              0.384615  0.625000  0.476190    8.000000
3              0.600000  0.375000  0.461538    8.000000
4              1.000000  0.125000  0.222222    8.000000
5              0.666667  0.750000  0.705882    8.000000
6              0.000000  0.000000  0.000000    8.000000
7              0.400000  0.285714  0.333333    7.000000
8              0.000000  0.000000  0.000000    8.000000
9              0.428571  0.375000  0.400000    8.000000
10             0.222222  0.250000  0.235294    8.000000
11             0.312500  0.625000  0.416667    8.000000
12             0.500000  0.125000  0.200000    8.000000
13             0.666667  0.500000  0.571429    8.000000
14             1.000000  0.625000  0.769231    8.000000
15             0.222222  0.250000  0.235294    8.000000
16             0.250000  0.125000  0.166667    8.000000
17             0.285714  0.750000  0.413793    8.000000
18             0.833333  0.714286  0.769231    7.000000
19             0.333333  0.250000  0.285714    8.000000
20             0.200000  0.125000  0.153846    8.000000
21             0.666667  0.750000  0.705882    8.000000
22             0.500000  0.625000  0.555556    8.000000
23             1.000000  1.000000  1.000000    7.000000
24             0.500000  0.250000  0.333333    8.000000
25             0.500000  0.166667  0.250000    6.000000
26             0.888889  0.666667  0.761905   12.000000
accuracy       0.409302  0.409302  0.409302    0.409302
macro avg      0.468396  0.405864  0.400535  215.000000
weighted avg   0.472073  0.409302  0.404468  215.000000

In [26]:
from sklearn.naive_bayes import GaussianNB
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
import pandas as pd

clf_nb = Pipeline([
    ("scaler", StandardScaler()),
    ("gnb", GaussianNB())
])

y_true_all_nb = []
y_pred_all_nb = []

for fold, (train_idx, test_idx) in enumerate(reidentification_cv(df_all), 1):

    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    clf_nb.fit(X_train, y_train)
    y_pred = clf_nb.predict(X_test)

    y_true_all_nb.extend(y_test)
    y_pred_all_nb.extend(y_pred)

report_nb = classification_report(
    y_true_all_nb,
    y_pred_all_nb,
    output_dict=True,
    zero_division=0
)

report_nb_df = pd.DataFrame(report_nb).transpose()
report_nb_df

              precision    recall  f1-score     support
0              0.000000  0.000000  0.000000    8.000000
1              0.222222  0.250000  0.235294    8.000000
2              0.125000  0.250000  0.166667    8.000000
3              0.000000  0.000000  0.000000    8.000000
4              0.000000  0.000000  0.000000    8.000000
5              0.250000  0.250000  0.250000    8.000000
6              0.000000  0.000000  0.000000    8.000000
7              0.000000  0.000000  0.000000    7.000000
8              0.047619  0.125000  0.068966    8.000000
9              1.000000  0.250000  0.400000    8.000000
10             0.000000  0.000000  0.000000    8.000000
11             0.333333  0.125000  0.181818    8.000000
12             1.000000  0.125000  0.222222    8.000000
13             0.000000  0.000000  0.000000    8.000000
14             1.000000  0.375000  0.545455    8.000000
15             0.250000  0.125000  0.166667    8.000000
16             0.000000  0.000000  0.000000    8.000000
17             0.142857  0.125000  0.133333    8.000000
18             1.000000  0.142857  0.250000    7.000000
19             0.000000  0.000000  0.000000    8.000000
20             0.000000  0.000000  0.000000    8.000000
21             0.000000  0.000000  0.000000    8.000000
22             0.166667  0.125000  0.142857    8.000000
23             1.000000  0.571429  0.727273    7.000000
24             0.000000  0.000000  0.000000    8.000000
25             0.000000  0.000000  0.000000    6.000000
26             0.310345  0.750000  0.439024   12.000000
accuracy       0.144186  0.144186  0.144186    0.144186
macro avg      0.253631  0.132937  0.145540  215.000000
weighted avg   0.251282  0.144186  0.149839  215.000000

In [27]:
comparison_df = pd.DataFrame({
    "LogReg_precision": report_df.loc["macro avg", "precision"],
    "LogReg_recall": report_df.loc["macro avg", "recall"],
    "LogReg_f1": report_df.loc["macro avg", "f1-score"],
    "SVM_precision": report_svm_df.loc["macro avg", "precision"],
    "SVM_recall": report_svm_df.loc["macro avg", "recall"],
    "SVM_f1": report_svm_df.loc["macro avg", "f1-score"],
    "Bayes_precision": report_nb_df.loc["macro avg", "precision"],
    "Bayes_recall": report_nb_df.loc["macro avg", "recall"],
    "Bayes_f1": report_nb_df.loc["macro avg", "f1-score"],

}, index=["macro avg"])

comparison_df

,LogReg_precision,LogReg_recall,LogReg_f1,SVM_precision,SVM_recall,SVM_f1,Bayes_precision,Bayes_recall,Bayes_f1
macro avg,0.583243,0.486111,0.508338,0.468396,0.405864,0.400535,0.253631,0.132937,0.14554

In [28]:
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
import numpy as np

def naive_bayes_reidentification_cv(X, y, cv_iterator, top_k=5):
    y_true = []
    y_pred = []
    y_topk = []

    for train_idx, test_idx in cv_iterator:
        X_train, X_test = X[train_idx], X[test_idx]
        y_train, y_test = y[train_idx], y[test_idx]

        model = Pipeline([
            ("scaler", StandardScaler()),
            ("gnb", GaussianNB())
        ])

        model.fit(X_train, y_train)

        # Top-1
        y_hat = model.predict(X_test)[0]
        y_true.append(y_test[0])
        y_pred.append(y_hat)

        # Top-k (re-identification relevant)
        proba = model.predict_proba(X_test)[0]
        classes = model.named_steps["gnb"].classes_
        topk = classes[np.argsort(proba)[::-1][:top_k]]
        y_topk.append(y_test[0] in topk)

    acc = accuracy_score(y_true, y_pred)
    topk_acc = np.mean(y_topk)

    return acc, topk_acc

In [29]:
acc, top5 = naive_bayes_reidentification_cv(
    X,
    y,
    reidentification_cv(df_all),
    top_k=5
)

print(f"Naive Bayes Accuracy: {acc:.3f}")
print(f"Naive Bayes Top-5 Accuracy: {top5:.3f}")

Naive Bayes Accuracy: 0.144
Naive Bayes Top-5 Accuracy: 0.353

In [30]:
def make_positive_pairs(X, y):
    pairs = []
    labels = []

    for patient in np.unique(y):
        idx = np.where(y == patient)[0]
        for i in range(len(idx)):
            for j in range(i + 1, len(idx)):
                pairs.append([X[idx[i]], X[idx[j]]])
                labels.append(1)

    return np.array(pairs), np.array(labels)

In [31]:
import random

def make_negative_pairs_random(X, y, n_pairs):
    pairs, labels = [], []
    patients = np.unique(y)

    for _ in range(n_pairs):
        p1, p2 = np.random.choice(patients, 2, replace=False)
        i = np.random.choice(np.where(y == p1)[0])
        j = np.random.choice(np.where(y == p2)[0])
        pairs.append([X[i], X[j]])
        labels.append(0)

    return np.array(pairs), np.array(labels)

In [32]:
def make_negative_pairs_hard(X, y, n_pairs, n_components=50):

    pca = PCA(n_components=n_components)
    X_pca = pca.fit_transform(X)

    D = euclidean_distances(X_pca, X_pca)
    mask = y[:, None] != y[None, :]
    D = np.where(mask, D, np.inf)

    pairs, labels = [], []

    flat_idx = np.argsort(D, axis=None)[:n_pairs]

    for idx in flat_idx:
        i, j = np.unravel_index(idx, D.shape)
        pairs.append([X[i], X[j]])
        labels.append(0)

    return np.array(pairs), np.array(labels)

In [33]:
df_noctrl = df_all[df_all["patient"] != "ZZ_control"].copy()
X_nc = np.vstack(df_noctrl["expression"].values)
y_nc = df_noctrl["patient"].values

In [39]:
def build_siamese_network(input_dim):
    inp = layers.Input(shape=(input_dim,))
    x = layers.Dense(256, activation="relu",
                     kernel_regularizer=regularizers.l2(1e-4))(inp)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.4)(x)

    x = layers.Dense(128, activation="relu",
                     kernel_regularizer=regularizers.l2(1e-4))(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.3)(x)

    x = layers.Dense(64, activation="relu")(x)
    embedding = layers.Lambda(lambda t: tf.math.l2_normalize(t, axis=1))(x)

    base = Model(inp, embedding, name="embedder")

    a = layers.Input(shape=(input_dim,))
    b = layers.Input(shape=(input_dim,))
    ea = base(a)
    eb = base(b)

    dist = layers.Lambda(lambda z: tf.reduce_sum(tf.square(z[0]-z[1]),
                                                 axis=1, keepdims=True))([ea, eb])
    out = layers.Dense(1, activation="sigmoid")(dist)

    model = Model([a, b], out)
    model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
                  loss="binary_crossentropy")
    return model, base

In [41]:
def predict_patient_embedding(embedder, x_test, X_train, y_train):
    z_test = embedder.predict(x_test.reshape(1,-1), verbose=0)
    Z_train = embedder.predict(X_train, verbose=0)
    d = euclidean_distances(z_test, Z_train)[0]
    df = pd.DataFrame({"patient": y_train, "dist": d})
    return df.groupby("patient")["dist"].mean().idxmin()

In [1]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

C:\Users\cihan\ki-al-miRNA-attack\venv\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

[]

In [42]:
y_true, y_pred = [], []

for train_idx, test_idx in reidentification_cv(df_noctrl):

    # --- split ---
    X_train, X_test = X_nc[train_idx], X_nc[test_idx]
    y_train, y_test = y_nc[train_idx], y_nc[test_idx]

    # --- pair generation (TRAIN only) ---
    Xp, yp = make_positive_pairs(X_train, y_train)
    Xn, yn = make_negative_pairs_hard(X_train, y_train, n_pairs=len(yp))

    X_pairs = np.vstack([Xp, Xn])
    y_pairs = np.hstack([yp, yn])

    # --- build model ---
    siamese, embedder = build_siamese_network(X_train.shape[1])

    # --- train ---
    siamese.fit(
        [X_pairs[:, 0], X_pairs[:, 1]],
        y_pairs,
        epochs=50,
        batch_size=32,
        verbose=0,
        callbacks=[
            tf.keras.callbacks.EarlyStopping(
                monitor="loss",
                patience=3,
                restore_best_weights=True
            )
        ]
    )

    # --- inference (embedding-based identification) ---
    pred = predict_patient_embedding(
        embedder,
        X_test[0],
        X_train,
        y_train
    )

    y_true.append(y_test[0])
    y_pred.append(pred)

print("\n=== Siamese Network (Leakage-Free, No ZZ_Control) ===\n")
print(classification_report(y_true, y_pred, zero_division=0))

KeyboardInterrupt:

In [ ]:

# --- reidentification CV (seninki) ---
def reidentification_cv(df):
    for patient, df_p in df.groupby("patient"):
        for test_idx in df_p.index:
            train_idx = df.index.difference([test_idx])
            yield train_idx.to_numpy(), np.array([test_idx])

# --- pair makers (seninki) ---
def make_positive_pairs(X, y):
    pairs, labels = [], []
    for p in np.unique(y):
        idx = np.where(y == p)[0]
        for i in range(len(idx)):
            for j in range(i + 1, len(idx)):
                pairs.append([X[idx[i]], X[idx[j]]])
                labels.append(1)
    return np.array(pairs), np.array(labels)

def make_negative_pairs_hard(X, y, n_pairs, n_components=50):
    pca = PCA(n_components=min(n_components, X.shape[1]))
    X_pca = pca.fit_transform(X)

    D = euclidean_distances(X_pca, X_pca)
    mask = y[:, None] != y[None, :]
    D = np.where(mask, D, np.inf)

    flat_idx = np.argsort(D, axis=None)[:n_pairs]
    pairs, labels = [], []
    for idx in flat_idx:
        i, j = np.unravel_index(idx, D.shape)
        pairs.append([X[i], X[j]])
        labels.append(0)
    return np.array(pairs), np.array(labels)

# --- siamese builder (seninki ama base'i ayrıca döndürüyorum) ---
def build_siamese(input_dim):
    inp = layers.Input(shape=(input_dim,))
    x = layers.Dense(256, activation="relu",
                     kernel_regularizer=regularizers.l2(1e-4))(inp)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.4)(x)

    x = layers.Dense(128, activation="relu",
                     kernel_regularizer=regularizers.l2(1e-4))(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.3)(x)

    x = layers.Dense(64, activation="relu")(x)
    embedding = layers.Lambda(lambda t: tf.math.l2_normalize(t, axis=1))(x)

    base = Model(inp, embedding, name="embedder")

    a = layers.Input(shape=(input_dim,))
    b = layers.Input(shape=(input_dim,))
    ea = base(a)
    eb = base(b)

    dist = layers.Lambda(lambda z: tf.reduce_sum(tf.square(z[0]-z[1]),
                                                 axis=1, keepdims=True))([ea, eb])
    out = layers.Dense(1, activation="sigmoid")(dist)

    model = Model([a, b], out)
    model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
                  loss="binary_crossentropy")
    return model, base

# --- embedding ile patient tahmini (mean distance) ---
def predict_patient_embedding(embedder, x_test, X_train, y_train):
    z_test = embedder.predict(x_test.reshape(1,-1), verbose=0)
    Z_train = embedder.predict(X_train, verbose=0)
    d = euclidean_distances(z_test, Z_train)[0]
    df = pd.DataFrame({"patient": y_train, "dist": d})
    return df.groupby("patient")["dist"].mean().idxmin()

# =========================
#   LEAKAGE-FREE EVAL
# =========================

# X ve y burada hazır olmalı:
# X = np.vstack(df_all["expression"].values)
# y = df_all["patient"].values  # string label önerilir

y_true, y_pred = [], []

for fold, (train_idx, test_idx) in enumerate(reidentification_cv(df_all), 1):
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    # pairs sadece TRAIN'den
    Xp, yp = make_positive_pairs(X_train, y_train)
    Xn, yn = make_negative_pairs_hard(X_train, y_train, n_pairs=len(yp))

    X_pairs = np.vstack([Xp, Xn])
    y_pairs = np.hstack([yp, yn])

    # her fold'da yeni model (doğru ama maliyetli)
    siamese, embedder = build_siamese(X_train.shape[1])

    siamese.fit(
        [X_pairs[:,0], X_pairs[:,1]],
        y_pairs,
        epochs=30,
        batch_size=64,
        verbose=0,
        callbacks=[
            tf.keras.callbacks.EarlyStopping(
                monitor="loss", patience=5, restore_best_weights=True
            )
        ],
    )

    pred = predict_patient_embedding(embedder, X_test[0], X_train, y_train)

    y_true.append(y_test[0])
    y_pred.append(pred)

print(classification_report(y_true, y_pred, zero_division=0))

In [ ]:
# Portfolio için tablo
results_final = pd.DataFrame({
    'Method': ['LogReg + PCA', 'SVM + PCA', 'Siamese + LogReg'],
    'Accuracy': [0.488, 0.409, 0.898],
    'F1-Score': [0.508, 0.401, 0.878],
    'Architecture': ['Linear', 'RBF Kernel', 'Deep Metric Learning'],
    'Embedding Dim': ['-', '-', '64D'],
    'Training Time': ['1 min', '2 min', '8 min']
})

In [ ]:
# t-SNE plot
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt

Z = embedder_hybrid.predict(X)
tsne = TSNE(n_components=2, random_state=42, perplexity=30)
Z_2d = tsne.fit_transform(Z)

plt.figure(figsize=(14, 10))
for i, p in enumerate(np.unique(y)):
    idx = y == p
    plt.scatter(Z_2d[idx, 0], Z_2d[idx, 1], 
                label=f'Patient {p}', alpha=0.7, s=100)
plt.legend(bbox_to_anchor=(1.05, 1), ncol=2)
plt.title('Siamese Embedding Space (t-SNE)', fontsize=16)
plt.xlabel('t-SNE 1')
plt.ylabel('t-SNE 2')
plt.tight_layout()
plt.savefig('siamese_tsne.png', dpi=300)
plt.show()

In [ ]:
from sklearn.metrics import confusion_matrix
import seaborn as sns

cm = confusion_matrix(y_true_hybrid, y_pred_hybrid)
plt.figure(figsize=(12, 10))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title('Hybrid Siamese Confusion Matrix')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=300)
plt.show()

In [ ]:
# Hangi hastalar zor?
from sklearn.metrics import classification_report

report = classification_report(y_true_hybrid, y_pred_hybrid, 
                               output_dict=True, zero_division=0)
per_class = pd.DataFrame(report).T[:-3]  # Exclude avg rows
per_class = per_class.sort_values('f1-score')

print("En zor 5 hasta:")
print(per_class.head())

print("\nEn kolay 5 hasta:")
print(per_class.tail())

In [ ]:
# BASLIYORUZ 31

In [ ]:
def reidentification_cv(df):
    """
    Each patient's each timepoint is once used as unknown test sample.
    All remaining samples form the leaked training set.
    """
    for patient, df_p in df.groupby("patient"):
        for test_idx in df_p.index:
            train_idx = df.index.difference([test_idx])
            yield train_idx.to_numpy(), np.array([test_idx])

In [ ]:
def make_positive_pairs(X, y):
    """
    All pairs from the same patient (positive pairs).
    """
    pairs, labels = [], []

    for p in np.unique(y):
        idx = np.where(y == p)[0]
        for i in range(len(idx)):
            for j in range(i + 1, len(idx)):
                pairs.append([X[idx[i]], X[idx[j]]])
                labels.append(1)

    return np.array(pairs), np.array(labels)

In [ ]:
def make_negative_pairs_hard(X, y, n_pairs, n_components=100):
    """
    Hard negative mining:
    select most similar pairs belonging to different patients.
    """

    pca = PCA(n_components=min(n_components, X.shape[1]))
    X_pca = pca.fit_transform(X)

    D = euclidean_distances(X_pca, X_pca)

    # mask same-patient pairs
    mask = y[:, None] != y[None, :]
    D = np.where(mask, D, np.inf)

    # select closest different-patient pairs
    flat_idx = np.argsort(D, axis=None)[:n_pairs]

    pairs, labels = [], []
    for idx in flat_idx:
        i, j = np.unravel_index(idx, D.shape)
        pairs.append([X[i], X[j]])
        labels.append(0)

    return np.array(pairs), np.array(labels)

In [ ]:
def make_negative_pairs_random(X, y, n_pairs):
    """
    Random negative pairs:
    randomly sampled pairs from different patients.
    Simulates a weaker attacker.
    """

    pairs, labels = [], []
    patients = np.unique(y)

    for _ in range(n_pairs):
        p1, p2 = np.random.choice(patients, 2, replace=False)
        i = np.random.choice(np.where(y == p1)[0])
        j = np.random.choice(np.where(y == p2)[0])

        pairs.append([X[i], X[j]])
        labels.append(0)

    return np.array(pairs), np.array(labels)

In [ ]:
def make_negative_pairs_hard(X, y, n_pairs, n_components=100):
    """
    Hard negative mining:
    select most similar pairs belonging to different patients.
    """

    pca = PCA(n_components=min(n_components, X.shape[1]))
    X_pca = pca.fit_transform(X)

    D = euclidean_distances(X_pca, X_pca)

    # mask same-patient pairs
    mask = y[:, None] != y[None, :]
    D = np.where(mask, D, np.inf)

    # select closest different-patient pairs
    flat_idx = np.argsort(D, axis=None)[:n_pairs]

    pairs, labels = [], []
    for idx in flat_idx:
        i, j = np.unravel_index(idx, D.shape)
        pairs.append([X[i], X[j]])
        labels.append(0)

    return np.array(pairs), np.array(labels)

In [ ]:
def build_siamese_network(input_dim):
    """
    Siamese network for metric learning on miRNA profiles.
    """

    # ---- Embedding network ----
    inp = layers.Input(shape=(input_dim,))
    
    x = layers.Dense(256, activation="relu",
                     kernel_regularizer=regularizers.l2(1e-4))(inp)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.3)(x)

    x = layers.Dense(128, activation="relu",
                     kernel_regularizer=regularizers.l2(1e-4))(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.3)(x)

    x = layers.Dense(64, activation="relu")(x)
    embedding = layers.Lambda(lambda t: tf.math.l2_normalize(t, axis=1))(x)

    embedder = Model(inp, embedding, name="embedder")

    # ---- Siamese structure ----
    a = layers.Input(shape=(input_dim,))
    b = layers.Input(shape=(input_dim,))

    ea = embedder(a)
    eb = embedder(b)

    dist = layers.Lambda(
        lambda z: tf.reduce_sum(tf.square(z[0] - z[1]), axis=1, keepdims=True)
    )([ea, eb])

    out = layers.Dense(1, activation="sigmoid")(dist)

    siamese = Model([a, b], out)
    siamese.compile(
        optimizer=tf.keras.optimizers.Adam(1e-3),
        loss="binary_crossentropy"
    )

    return siamese, embedder

In [ ]:
def predict_patient_embedding(embedder, x_test, X_train, y_train):
    """
    Identify patient by nearest mean embedding distance.
    """

    z_test = embedder.predict(x_test.reshape(1, -1), verbose=0)
    Z_train = embedder.predict(X_train, verbose=0)

    dists = euclidean_distances(z_test, Z_train)[0]

    df = pd.DataFrame({
        "patient": y_train,
        "dist": dists
    })

    return df.groupby("patient")["dist"].mean().idxmin()

In [ ]:
y_true, y_pred = [], []

for train_idx, test_idx in reidentification_cv(df_all):

    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    # pairs only from leaked training data
    Xp, yp = make_positive_pairs(X_train, y_train)
    Xn, yn = make_negative_pairs_hard(X_train, y_train, n_pairs=len(yp))

    X_pairs = np.vstack([Xp, Xn])
    y_pairs = np.hstack([yp, yn])

    siamese, embedder = build_siamese_network(X_train.shape[1])

    siamese.fit(
        [X_pairs[:,0], X_pairs[:,1]],
        y_pairs,
        epochs=50,
        batch_size=64,
        verbose=0,
        callbacks=[
            tf.keras.callbacks.EarlyStopping(
                monitor="loss", patience=5, restore_best_weights=True
            )
        ]
    )

    pred = predict_patient_embedding(embedder, X_test[0], X_train, y_train)

    y_true.append(y_test[0])
    y_pred.append(pred)

print("\n=== Leakage-Free Strong Attacker ===\n")
print(classification_report(y_true, y_pred, zero_division=0))

In [ ]:
# Train once on ALL data (intentional leakage)
Xp, yp = make_positive_pairs(X, y)
Xn, yn = make_negative_pairs_hard(X, y, n_pairs=len(yp)*3)

X_pairs = np.vstack([Xp, Xn])
y_pairs = np.hstack([yp, yn])

siamese, embedder = build_siamese_network(X.shape[1])

siamese.fit(
    [X_pairs[:,0], X_pairs[:,1]],
    y_pairs,
    epochs=50,
    batch_size=64,
    validation_split=0.15,
    verbose=1,
    callbacks=[
        tf.keras.callbacks.EarlyStopping(
            monitor="val_loss", patience=10, restore_best_weights=True
        )
    ]
)

# evaluate
y_true, y_pred = [], []

for train_idx, test_idx in reidentification_cv(df_all):
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    pred = predict_patient_embedding(embedder, X_test[0], X_train, y_train)

    y_true.append(y_test[0])
    y_pred.append(pred)

print("\n=== Leak-Aware Upper-Bound Attacker ===\n")
print(classification_report(y_true, y_pred, zero_division=0))

In [ ]:
y_true, y_pred = [], []

for train_idx, test_idx in reidentification_cv(df_all):

    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    # pairs only from leaked training data
    Xp, yp = make_positive_pairs(X_train, y_train)
    Xn, yn = make_negative_pairs_random(X_train, y_train, n_pairs=len(yp))

    X_pairs = np.vstack([Xp, Xn])
    y_pairs = np.hstack([yp, yn])

    siamese, embedder = build_siamese_network(X_train.shape[1])

    siamese.fit(
        [X_pairs[:,0], X_pairs[:,1]],
        y_pairs,
        epochs=25,
        batch_size=64,
        verbose=0,
        callbacks=[
            tf.keras.callbacks.EarlyStopping(
                monitor="loss", patience=5, restore_best_weights=True
            )
        ]
    )

    pred = predict_patient_embedding(embedder, X_test[0], X_train, y_train)

    y_true.append(y_test[0])
    y_pred.append(pred)

print("\n=== Leakage-Free WEAK Attacker (Random Negatives) ===\n")
print(classification_report(y_true, y_pred, zero_division=0))

In [ ]:
def reidentification_cv(df):
    """
    Each patient's each timepoint is once used as unknown test sample.
    All remaining samples form the leaked training set.
    """
    for patient, df_p in df.groupby("patient"):
        for test_idx in df_p.index:
            train_idx = df.index.difference([test_idx])
            yield train_idx.to_numpy(), np.array([test_idx])

In [ ]:
def make_positive_pairs(X, y):
    """
    All pairs from the same patient (positive pairs).
    """
    pairs, labels = [], []

    for p in np.unique(y):
        idx = np.where(y == p)[0]
        for i in range(len(idx)):
            for j in range(i + 1, len(idx)):
                pairs.append([X[idx[i]], X[idx[j]]])
                labels.append(1)

    return np.array(pairs), np.array(labels)

In [ ]:
def make_negative_pairs_random(X, y, n_pairs):
    """
    Random negative pairs:
    randomly sampled pairs from different patients.
    Simulates a weaker attacker.
    """
    pairs, labels = [], []
    patients = np.unique(y)

    for _ in range(n_pairs):
        p1, p2 = np.random.choice(patients, 2, replace=False)
        i = np.random.choice(np.where(y == p1)[0])
        j = np.random.choice(np.where(y == p2)[0])

        pairs.append([X[i], X[j]])
        labels.append(0)

    return np.array(pairs), np.array(labels)

In [ ]:
def make_negative_pairs_hard(X, y, n_pairs, n_components=100):
    """
    Hard negative mining:
    select most similar pairs belonging to different patients.
    """

    pca = PCA(n_components=min(n_components, X.shape[1]))
    X_pca = pca.fit_transform(X)

    D = euclidean_distances(X_pca, X_pca)

    # mask same-patient pairs
    mask = y[:, None] != y[None, :]
    D = np.where(mask, D, np.inf)

    flat_idx = np.argsort(D, axis=None)[:n_pairs]

    pairs, labels = [], []
    for idx in flat_idx:
        i, j = np.unravel_index(idx, D.shape)
        pairs.append([X[i], X[j]])
        labels.append(0)

    return np.array(pairs), np.array(labels)

In [ ]:
def build_siamese_network(input_dim):
    """
    Siamese network for metric learning on miRNA profiles.
    """

    # ---- Embedding network ----
    inp = layers.Input(shape=(input_dim,))
    
    x = layers.Dense(256, activation="relu",
                     kernel_regularizer=regularizers.l2(1e-4))(inp)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.3)(x)

    x = layers.Dense(128, activation="relu",
                     kernel_regularizer=regularizers.l2(1e-4))(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.3)(x)

    x = layers.Dense(64, activation="relu")(x)
    embedding = layers.Lambda(
        lambda t: tf.math.l2_normalize(t, axis=1)
    )(x)

    embedder = Model(inp, embedding, name="embedder")

    # ---- Siamese structure ----
    a = layers.Input(shape=(input_dim,))
    b = layers.Input(shape=(input_dim,))

    ea = embedder(a)
    eb = embedder(b)

    dist = layers.Lambda(
        lambda z: tf.reduce_sum(tf.square(z[0] - z[1]), axis=1, keepdims=True)
    )([ea, eb])

    out = layers.Dense(1, activation="sigmoid")(dist)

    siamese = Model([a, b], out)
    siamese.compile(
        optimizer=tf.keras.optimizers.Adam(1e-3),
        loss="binary_crossentropy"
    )

    return siamese, embedder